In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import scipy.optimize as opt
import scipy.linalg as linalg
import sklearn.linear_model
import sklearn.model_selection
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.datasets import load_iris
from IPython.display import Markdown as md

# Applied Machine Learning

## Recommenders and embeddings

### Recommender systems

- The main goal: predict the rating (preference, score, ..) that a user $u$ would give to some item $i$
- Important part of any massive online service
- A huge field of study
- Let us consider the classic user-movie setting

### Two approaches

- Model user-item interaction directly (content-based)
- Model user-user interaction to predict items (collaborative filtering)

### Content-based recommenders

- The rating problem is cast to classification
- Collect user actions (mouseovers, clicks, likes, whatever)
- User features: genres user interacted with, countries of movies they did like, etc
- Movie features: category, year, country, etc
- Combine these two sets of features and predict if they match

### Toy example

We have a set of users with counts of each genre assigned:

In [3]:
users = [
    {'comedy': 2, 'action': 1},
    {'documentary': 1, 'action': 1}, 
    {'comedy': 3}
]

Let's vectorize them:

In [4]:
from sklearn.feature_extraction import DictVectorizer
vectorizer = DictVectorizer().fit(users)

vectorizer.transform(users).todense()

matrix([[1., 2., 0.],
        [1., 0., 1.],
        [0., 3., 0.]])

In [5]:
genres = vectorizer.feature_names_
genres

['action', 'comedy', 'documentary']

In [6]:
features, labels = [], []
for user in users:
    for genre in genres:
        label = +1 if genre in user else -1
        user_features = np.ravel(vectorizer.transform(user).todense())
        item_features = np.ravel(vectorizer.transform({genre: 1}).todense())
        features.append(np.concatenate((user_features, item_features)))
        labels.append(label)
        
features = np.vstack(features)
labels = np.array(labels)

We've got a feature matrix and a labels vector:

In [7]:
print('Features', features)
print('Labels', labels.T)

# positives: likes/interactions/etc (scarce, not a lot of them) ~ millions
# negatives: in naïve ~ billions, find out good negatives ~ millions 

#user = [6.2, 4.5, ...] <- decision trees, neural networks, ...
#item = [1.2, 4.1, ...]
#[user + item], label 

Features [[1. 2. 0. 1. 0. 0.]
 [1. 2. 0. 0. 1. 0.]
 [1. 2. 0. 0. 0. 1.]
 [1. 0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 0. 1.]
 [0. 3. 0. 1. 0. 0.]
 [0. 3. 0. 0. 1. 0.]
 [0. 3. 0. 0. 0. 1.]]
Labels [ 1  1 -1  1 -1  1 -1  1 -1]


You know the next step

In [8]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression().fit(features, labels)

### Simple content-based model

- Our model obviously learns some tautology
- Although it also tends to learn dependencies between genres
- Given good features and good classifier such a model would produce quite good results

In [9]:
lr.predict(np.array([1, 0, 0, 0, 0, 1]).reshape(-1, 1).T)

array([1])

In [10]:
lr.predict_proba(np.array([1, 0, 0, 0, 0, 1]).reshape(-1, 1).T)

array([[0.40921065, 0.59078935]])

### Pitfalls

- Train set is rather high-maintenance (you need proper positive and negative examples)
- Feature engineering is very important
- Scalability might become a problem
- Can you leverage other users?

### Collaborative filtering (CF)

- Another approach for recommenders leveraging user-user relations
- Could be user-centric or item-centric
- User-centric: given a user, find other like-minded users and use their ratings

### User-item rating matrix

In [11]:
likes = ('Lliane', 'Titanic', 4), ('Roxanne', 'Titanic', 5), ('Roxanne', 'Ghost', 4)
users = {name: idx for (idx, name) in enumerate({x[0] for x in likes})}
items = {name: idx for (idx, name) in enumerate({x[1] for x in likes})}

R = np.zeros((len(users), len(items)))
for user, item, score in likes:
    R[users[user], items[item]] = score
R

array([[0., 4.],
       [4., 5.]])

### Memory-based CF

- The simplest approach to fill in missed ratings is:
$
R(user, item) = \mathop{avg}_{\text{item}~x} R(user, x)
$
- Let's try to clarify using other users:
$R(user, item) = \mathop{avg}_{\text{item}~x} R(user, x) + \mathop{avg}_{\text{other users}~u} \left(R(u, item) - \mathop{avg}_{\text{item}~x} R(u, x)\right)$
- Everybody likes Shawshank's Redemption so should you

In [12]:
R

Rating(Lianne, Titanic) = 4 (Lianne's usual rating) + avg(-0.5, 0, -0.5) = 3 2/3

 Lianne  Roxanne   John    Ann
[0,      4,        1,      3
 4,      5,        1,      4]

array([[0., 4.],
       [4., 5.]])

### Memory-base CF with similarity

- What if we had a function $S$ to measure similarity between users?
- The scoring rule would become:
$
R(user, item) = \mathop{avg}_{\text{item}~x} R(user, x) + \frac{1}{\text{normalizer}} \sum_{\text{other users}~u} S(user, u) \left(R(u, item) - \mathop{avg}_{\text{item}~x} R(u, x)\right)
$
- What is $S$?

### Pearson similarity

$S(u_1, u_2) = \frac{\sum_{item} \left(R(u_1, item) - \mathop{avg}_{x} R(u_1, x)\right) \left((R(u_2, item) - \mathop{avg}_{x} R(u_2, x)\right)}{\sqrt{\sum_{item} \left(R(u_1, item) - \mathop{avg}_{x} R(u_1, x)\right)^2} \sqrt{\sum_{item}\left(R(u_2, item) - \mathop{avg}_{x} R(u_2, x)\right)^2} }$

- Sums are computed on items rated by both of the users 
- Measures if users $u_1$ and $u_2$ often agree on the high and the low ratings
- Normalized using user's average rating

### Centricity

- We considered a model that measures users similarity (user-centric)
- Everything can be transposed to compute items similarity (item-centric)
- There is no single solution

### Matrix factorization

- A technique from linear algebra
- The matrix $X$ can be factorized into a product of matrices with some properties
- One of the most famous is LU and the other one is SVD

### LU decomposition

Useful to solve linear systems, $X=PLU$

In [13]:
X = np.array([[1, 2], [3, 4]])
P, L, U = linalg.lu(X)
print('P', P)
print('L', L)
print('U', U)
print('PLU', P.dot(L).dot(U))

P [[0. 1.]
 [1. 0.]]
L [[1.         0.        ]
 [0.33333333 1.        ]]
U [[3.         4.        ]
 [0.         0.66666667]]
PLU [[1. 2.]
 [3. 4.]]


### Singular Value Decomposition

Finds structure in matrix you don't see, $X=U\Sigma V^{T}$

In [21]:
U, s, Vh = linalg.svd(X, full_matrices=False)
U.dot(np.diag(s)).dot(Vh)
U, s, Vh

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

### Low-rank SVD decomposition

$U$, $\Sigma$, $V^{T}$ are of the same size as $X$ but we can cut them and still get something reasonable

In [15]:
np.outer(U[:, 0].dot(s[0]), Vh[0])

array([[1.27357371, 1.80720735],
       [2.87897923, 4.08528566]])

We lost some information but kept something basic

### Low-rank decomposition

- We can find matrices $U, I$ such that $R \sim U I$
- $R$ is of size #users x #items
- $U$ might be of size #users x $d$
- $I$ might be of size #items x $d$
- $d$ is a small number (3 - 10)
- Such a decomposition is not exact but useful, it tries to capture the essential information

### Embeddings

- The $U$ matrix contains a vector for each user (4.5, -2.3, 6.7)
- The $I$ matrix contains a vector for each item (-9.8, 7.5, 1.2)
- These vectors are also called embeddings
- The idea to vectorize everything was so hot it is still so

### Embeddings

In [29]:
users = {
    'Lliane': [9.7, 5.4, -3.2],
    'Roxanne': [0.9, 0.1, 0.2],
}
items = {
    'Titanic': [3.7, -0.5, 8.9],
    'Other movie': [...]
}
sorted(np.array(users['Lliane']).dot(np.array(items[x])) for x in items)
score

4.709999999999996

### Real-world recommenders

- Usually hybrid with a lot of running parts
- Different ways to introduce contextual information
- A lot of nuances to consider: train data, features, etc
- Additional metrics like diversity and serendipity
- Filter bubble and other problems

### PMI matrix

- Pointwise mutual information: $\log \frac{P(u, v)}{P(u) P(v)}$
- Measures how often $u, v$ happen together compared to discretely
- Becomes an interesting tool if $u, v$ are some language's words

### PMI matrix decomposition

- It is long known that PMI matrix could provide useful insights on words
- One obvious thing was to factorize it the same way we did with ratings
- What if we had embeddings for words?

### Word embeddings

Similar to user-items setting:

In [17]:
words = {
    'Moscow': [4.2, 2.4],
    'St. Petersburg': [-3.4, 2.3],
    'New York': [-2.3, -3.1],
    'Washington': [3.3, -2.7],
}
np.array(words['Moscow']).dot(np.array(words['Washington']))

7.379999999999999

### Word embedding

- Factorizing PMI sounds like a promising thing
- Nobody knew how to do that properly and it didn't work well
- The key was to consider PMI between words and "contexts"

### Word2vec

- Introduced in 2013 and started a revolution
- Small program made in totally unreadable C
- Consists of two regimes: skip-gram and Continuous Bag of Words (CBoW)
- Considers word contexts $\dots, w_{i-3}, w_{i-2}, w_{i-1}, \mathbf{w_{i}}, w_{i+1}, w_{i+2}, w_{i+3}, \dots$

### Skip-gram

$\dots, w_{i-3}, w_{i-2}, w_{i-1}, \mathbf{w_{i}}, w_{i+1}, w_{i+2}, w_{i+3}, \dots$
- For any context, $w_i$ is fixed
- We try to fit $w_{j}$ so that it is similar to $w_i$
- Learn to predict the context given a word

### Continuous Bag of Words

$\dots, w_{i-3}, w_{i-2}, w_{i-1}, \mathbf{w_{i}}, w_{i+1}, w_{i+2}, w_{i+3}, \dots$

- For any context, everything but $w_i$ is fixed
- We try to ... vector of $w_i$ to the vector of context
- Learn to predict the word given a context

### What do we get?

In [30]:
from gensim.models import KeyedVectors
model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True)

In [33]:
model.get_vector('machine')[:50]

array([ 0.25585938, -0.02209473,  0.02905273,  0.05444336, -0.07421875,
        0.35351562, -0.06347656,  0.14453125,  0.07226562,  0.10009766,
       -0.18261719, -0.22851562,  0.02209473, -0.22070312,  0.19140625,
        0.19140625, -0.16699219,  0.16796875,  0.29492188, -0.18066406,
       -0.01452637,  0.10742188, -0.16503906,  0.29882812,  0.12988281,
       -0.1171875 , -0.16796875,  0.1015625 ,  0.04492188, -0.12060547,
        0.07470703, -0.34765625, -0.10107422,  0.38085938, -0.20605469,
       -0.07470703, -0.10839844,  0.18652344,  0.20117188, -0.02124023,
        0.28515625, -0.09277344,  0.13964844,  0.05786133,  0.26757812,
       -0.15039062, -0.08544922,  0.19238281,  0.08007812,  0.06396484],
      dtype=float32)

### Algebra of vectors

The vectors we learn in word2vec are actually following some algebraic rules

In [34]:
model.most_similar(positive=['learning'])

[('teaching', 0.6601868271827698),
 ('learn', 0.6365276575088501),
 ('Learning', 0.6208059191703796),
 ('reteaching', 0.5809674263000488),
 ('learner_centered', 0.5738571286201477),
 ('emergent_literacy', 0.5706571340560913),
 ('teach', 0.5704740881919861),
 ('kinesthetic_learning', 0.5656599998474121),
 ('learners', 0.5508513450622559),
 ('learing', 0.5438815355300903)]

### Learning embeddings

- Once we have the objective (skip-gram or CBoW) it is possible to employ optimization
- Optimization refines the embeddings so that they fit together better
- In the end, you get a lookup table (word -> vector)

### fastText

- Very similar thing to word2vec
- Consider character n-grams 
- This enables capturing some language structure

In [22]:
word = 'character'
[word[i:i+3] for i in range(len(word) - 2)]

['cha', 'har', 'ara', 'rac', 'act', 'cte', 'ter']

### PMI?

- All the methods for finding word embeddings are doing something similar
- It is some equivalent of the PMI matrix factorization
- Not really an important issue for practicioners

### Word embeddings in practice

- One doesn't really need to train word embeddings
- Just google 'pretrained word2vec' or 'pretrained fasttext' and enjoy the results

### Practical considerations

- To embed sentences just sum the word embeddings
- Do not forget to normalize the embeddings
- Each component of embedding is important, hints for neural networks and linear models
- You can actually embed URLs the same way

### Next class

- Non-parametric methods
- k nearest neighbor
- k-means